version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: flight_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: flight_management
    ports:
      - "5432:5432"
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    restart: unless-stopped